baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "fr-FR"
title = "Pierre-Alexandre Bardina's blog"
theme = "hyde-x"

[author]
  name = "Pierre-Alexandre Bardina"

[params]
  github = "https://github.com/pabardina"
  linkedin = "https://www.linkedin.com/in/pabardina"
  twitter = "https://www.twitter.com/pabardina"
  tagline = "En perpétuelle évolution"
  theme = "theme-base-0c"
  home = "Blog"
  highlight = "sunburst"
