baseurl = "https://www.bardina.net/"
languageCode = "fr-FR"
title = "Pierre-Alexandre Bardina's blog"
theme = "ghostwriter"
googleAnalytics = "UA-51313447-1"

[Author]
  name = "Pierre-Alexandre Bardina"

[Params]
  github = "https://github.com/pabardina"
  linkedin = "https://www.linkedin.com/in/pabardina"
  twitter = "https://www.twitter.com/pabardina"
  tagline = "En perpétuelle évolution"
  home = "Blog"
  highlight = "sunburst"

[Permalinks]
    post = "/:filename"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
